version: 2.1

defaults: &defaults 
  docker: 
    - image: circleci/node:13.8.0
  

jobs:
  
  build-job:
    <<: *defaults
    steps:
      - run: 
          name: run build
          command: npm i
      - save-cache:
          key: dependencies-cache
          paths: /src/node-modules
      - run:
          name: run lint  
          command: npm run list






workflows:
  default: ## workflow name
    jobs:
      - build-job          
      