version: 2.1

defaults: &defaults  ## using an anchor at the beginning of .circleci/config.yml to set these lines as our default for jobs:
  docker: 
    - image: circleci/node:13.8.0
  

jobs:
  
  build-job:
    <<: *defaults  ## Then we use an alias with each job to write less lines. Here’s an example using the build-job job from earlier:
    steps:
      - checkout
      - run: 
          name: run build
          command: npm i
      - save_cache:
          key: "dependencies-cache"
          paths: /src/node_modules
      - run:
          name: run lint  
          command: npm run lint

  test-job: ## Then we use an alias with each job to write less lines. Here’s an example using the test-job job from earlier:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: "dependencies-cache"
      - run: npm i
      - run: npm run test

  analyze-job:
    <<: *defaults ## Then we use an alias with each job to write less lines. Here’s an example using the analyze-job job from earlier:
    steps:
      - checkout
      - restore_cache:
          key: "dependencies-cache"
      - run:
          name: fix code dependencies
          command: |
            npm audit fix
            npm audit fix --audit-level=critical --force            
            npm audit --audit-level=critical

workflows:
  default: ## workflow name
    jobs:
      - build-job     
      - test-job:
          requires: [build-job]
      - analyze-job:
          requires: [test-job]
      
