version: 2.1

defaults: &defaults 
  docker: 
    - image: circleci/node:13.8.0
  

jobs:
  
  build-job:
    <<: *defaults
    steps:
      - checkout
      - run: 
          name: run build
          command: npm i
      - save_cache:
          key: "dependencies-cache"
          paths: /src/node_modules
      - run:
          name: run lint  
          command: npm run lint

  test-job:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: "dependencies-cache"
      - run: npm i
      - run: npm run test

  analyze-job:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: "dependencies-cache"
      - run:
          name: fix code dependencies
          command: |
            npm audit fix --audit-level=critical --force            
            npm audit --audit-level=critical

workflows:
  default: ## workflow name
    jobs:
      - build-job     
      - test-job:
          requires: [build-job]
      - analyze-job:
          requires: [test-job]
      

# version: 2.1
# jobs:
#   build: # build job
#     docker: 
#       - image: circleci/node:13.8.0
#     steps: ## commands/instrcutions to build the test job
#       - checkout
#       - run: npm i 
#       - run: npm run lint

#   test: # test job
#     docker:
#       - image: circleci/node:13.8.0
#     steps:
#       - checkout
#       - run: npm i
#       - run: npm run test
    
#   analyze: # analyze job
#     docker: 
#       - image: circleci/node:13.8.0
#     steps:
#       - checkout
#       - run: npm audit

# workflows:  # workflow job
#   my_workflow:
#     jobs: # This my_workflow job means the analyze job requires test job to run likewise the test job require the build job to run first.
#       - build
#       - test:
#           requires:
#             - build
#       - analyze:
#           requires:
            # - test      